Repository J-P-plan/J-P_FE2, pull requests merged in 2024-12, with the labels that each got.

#67 일정 플랜 부분 구현, 리뷰 api 연동, types 폴더 수정
  src/components/DaySlider.tsx
  src/components/MoveDaySlider.tsx
  src/components/mobile/CommentCard.tsx
  src/components/mobile/ReviewCard.tsx
  src/components/mobile/bottomSheets/TravelPlaceAddSheet.tsx
  src/components/mobile/googleMap/RenderGoogleMap.tsx
  src/components/mobile/home/CardSlide.tsx
  src/components/web/home/CardSlide.tsx
  src/components/web/schedule/AddPlaceCard.tsx
  src/components/web/schedule/PlanItem.tsx
  src/components/web/surroundingPlace/TravelPlaceAddModal.tsx
  src/components/web/travel-review/ReviewCard.tsx
  src/components/web/travel-review/TravelogueCard.tsx
  src/hooks/useAddPlace.tsx
  src/hooks/useSearch.tsx
  src/pages/mobile/details/HomeDetails.tsx
  src/pages/mobile/details/NearPlace.tsx
  src/pages/mobile/details/Reviews.tsx
  src/pages/mobile/home/Home.tsx
  src/pages/mobile/home/More.tsx
  src/pages/mobile/search/Search.tsx
  src/pages/mobile/travel-review/Review.tsx
  src/pages/mobile/travel-review/ReviewDetails.tsx
  src/pages/mobile/travel-review/TravelReview.tsx
  src/pages/mobile/travel-review/Travelogue.tsx
  src/pages/web/detail/Detail.tsx
  src/pages/web/detail/SurroundingMore.tsx
  src/pages/web/home/More.tsx
  src/pages/web/schedule/CreatePlace.tsx
  src/pages/web/schedule/ScheduleDetails.tsx
  src/pages/web/travel-review/Review.tsx
  src/pages/web/travel-review/ReviewDetails.tsx
  src/pages/web/travel-review/Travelogue.tsx
  src/service/axios.ts
  src/store/map.store.ts
  src/types/axios.type.ts
  src/types/home.ts
  src/types/mypage.ts
  src/types/place.ts
  src/types/res.dto.ts
  src/types/schedule.ts
  src/utils/staticDatas.ts
Labels: feat, chore

#68 types 폴더 수정
  src/types/travelreview.ts
Labels: chore

#69 feat: 구글맵 지도 1,2,3,4 순서 & 타입 폴더 정리 해야함
  package-lock.json
  package.json
  src/assets/icons/PhoneIcon.tsx
  src/components/DaySlider.tsx
  src/components/JPToggle.tsx
  src/components/mobile/bottomSheets/PlanSheet.tsx
  src/components/mobile/bottomSheets/TravelPlaceAddSheet.tsx
  src/components/mobile/googleMap/CustomGoogleMap.tsx
  src/components/mobile/googleMap/RenderGoogleMap.tsx
  src/components/mobile/schedule/PlanItem.tsx
  src/components/mobile/schedule/PlanList.tsx
  src/components/web/schedule/AddPlaceCard.tsx
  src/components/web/schedule/PlanItem.tsx
  src/components/web/schedule/UpcomingSchedule.tsx
  src/components/web/surroundingPlace/TravelPlaceAddModal.tsx
  src/pages/web/detail/Detail.tsx
  src/pages/web/onboarding/Onboarding.tsx
  src/pages/web/onboarding/Survey.tsx
  src/pages/web/schedule/CreatePlace.tsx
  src/pages/web/schedule/ScheduleDetails.tsx
  src/store/JPType.store.ts
  src/store/map.store.ts
  src/types/schedule.ts
  src/utils/dateUtils.ts
Labels: feat

#70 feat: types 폴더 정리 & 일정 상세 페이지 지도 구현
  package-lock.json
  package.json
  src/assets/styles/home.style.ts
  src/assets/styles/scheduleDetail.style.ts
  src/components/DaySlider.tsx
  src/components/mobile/bottomSheets/TravelPlaceAddSheet.tsx
  src/components/mobile/googleMap/CustomGoogleMap.tsx
  src/components/mobile/googleMap/RenderGoogleMap.tsx
  src/components/web/home/CardSlide.tsx
  src/components/web/home/SurroundingMoreAddCard.tsx
  src/components/web/surroundingPlace/TravelPlaceAddModal.tsx
  src/hooks/useImagesUpload.tsx
  src/pages/mobile/schedule/Calendar.tsx
  src/pages/mobile/schedule/Details.tsx
  src/pages/web/detail/SurroundingMore.tsx
  src/pages/web/schedule/ScheduleDetails.tsx
  src/types/common.ts
  src/types/schedule.ts
  src/types/styled.d.ts
  src/utils/staticDatas.ts
Labels: feat

#71 feat: 여행기 작성, 수정
  src/components/web/mypage/MyScheduleCard.tsx
  src/components/web/mypage/SelectTravelModal.tsx
  src/components/web/mypage/SortablePhoto.tsx
  src/hooks/useImagesUpload.tsx
  src/pages/web/mypage/MyTravelogue.tsx
  src/pages/web/mypage/WriteTravelouge.tsx
  src/pages/web/router.tsx
  src/pages/web/travel-review/TravelReview.tsx
  src/pages/web/travel-review/Travelogue.tsx
  src/service/axios.ts
  src/utils/dayNights.ts
Labels: feat

#73 feat: 일정 기능 구현, 여행기 api 연동
  src/assets/styles/nearplace.style.ts
  src/assets/styles/scheduleDetail.style.ts
  src/components/DaySlider.tsx
  src/components/MoveDaySlider.tsx
  src/components/TimeSwiper.tsx
  src/components/TransportBox.tsx
  src/components/mobile/ImageSlider.tsx
  src/components/mobile/bottomSheets/PlanPlaceSheet.tsx
  src/components/mobile/bottomSheets/PlanSheet.tsx
  src/components/mobile/schedule/PlanItem.tsx
  src/components/mobile/schedule/PlanMemo.tsx
  src/components/mobile/travelReview/TravelogueCard.tsx
  src/components/web/schedule/PlanItem.tsx
  src/components/web/schedule/PlanMemo.tsx
  src/components/web/travel-review/TravelogueCard.tsx
  src/components/web/travel-review/TwoImageBox.tsx
  src/pages/mobile/router.tsx
  src/pages/mobile/schedule/Details.tsx
  src/pages/mobile/travel-review/Travelogue.tsx
  src/pages/mobile/travel-review/TravelogueDetails.tsx
  src/pages/web/schedule/ScheduleDetails.tsx
  src/pages/web/travel-review/ImageViewer.tsx
  src/pages/web/travel-review/Travelogue.tsx
  src/pages/web/travel-review/TravelogueDetails.tsx
  src/service/axios.ts
  src/store/currentDayId.store.ts
  src/store/selectPlanItem.store.ts
  src/store/useAddPlace.store.ts
  src/types/schedule.ts
Labels: feat

#74 chore: useAddPlaceStore -> useAddPlaceHook 수정
  src/assets/icons/EditIcon.tsx
  src/components/MoveDaySlider.tsx
  src/components/TimeSwiper.tsx
  src/components/mobile/bottomSheets/PlanPlaceSheet.tsx
  src/components/mobile/bottomSheets/PlanSheet.tsx
  src/components/mobile/schedule/PlanItem.tsx
  src/components/web/ImageView.tsx
  src/components/web/home/CardSlide.tsx
  src/components/web/home/PlaceCard.tsx
  src/components/web/mypage/AddPlaceCard.tsx
  src/components/web/mypage/ReviewCard.tsx
  src/components/web/mypage/SelectPlaceBar.tsx
  src/components/web/schedule/AddPlaceCard.tsx
  src/components/web/schedule/AddedPlaceDetailModal.tsx
  src/components/web/schedule/PlanItem.tsx
  src/components/web/schedule/PlanMemo.tsx
  src/components/web/schedule/RecommendCard.tsx
  src/components/web/schedule/UpcomingSchedule.tsx
  src/components/web/search/ResultsCard.tsx
  src/components/web/search/SearchBar.tsx
  src/components/web/surroundingPlace/InfoModal.tsx
  src/components/web/surroundingPlace/TravelPlaceAddModal.tsx
  src/components/web/travel-review/ReviewCard.tsx
  src/hooks/useSearch.tsx
  src/pages/mobile/addPlace/ListView.tsx
  src/pages/web/detail/Detail.tsx
  src/pages/web/detail/ReviewMore.tsx
  src/pages/web/detail/SurroundingMore.tsx
  src/pages/web/home/Home.tsx
  src/pages/web/home/More.tsx
  src/pages/web/mypage/MyReviews.tsx
  src/pages/web/mypage/WriteReview.tsx
  src/pages/web/mypage/WriteTravelouge.tsx
  src/pages/web/router.tsx
  src/pages/web/schedule/CreatePlace.tsx
  src/pages/web/search/Search.tsx
  src/pages/web/travel-review/ImageViewer.tsx
  src/pages/web/travel-review/ReviewDetails.tsx
  src/pages/web/travel-review/Travelogue.tsx
  src/service/axios.ts
  src/store/useAddPlace.store.ts
  src/store/writeReview.store.ts
  src/types/mypage.ts
  src/types/place.ts
  src/types/search.ts
  src/types/travelreview.ts
Labels: chore

#75 feat: 리뷰 댓글, 대댓글 하는 중 & 마이페이지 내 찜 목록
  src/assets/styles/travelReview.style.ts
  src/components/IconBox.tsx
  src/components/mobile/CommentCard.tsx
  src/components/web/mypage/ReviewCard.tsx
  src/components/web/schedule/AddPlaceCard.tsx
  src/components/web/schedule/AddedPlaceDetailModal.tsx
  src/components/web/schedule/PlanItem.tsx
  src/components/web/schedule/ScheduleSlider.tsx
  src/components/web/schedule/UpcomingSchedule.tsx
  src/pages/web/detail/Detail.tsx
  src/pages/web/mypage/MyLikes.tsx
  src/pages/web/mypage/MyReviews.tsx
  src/pages/web/travel-review/ReviewDetails.tsx
  src/pages/web/travel-review/TravelogueDetails.tsx
  src/service/axios.ts
  src/types/mypage.ts
  src/types/travelreview.ts
Labels: feat

#76 fix: axios header 안들어가지는 문제 수정
  src/components/web/schedule/UpcomingSchedule.tsx
  src/service/axios.ts
Labels: bug

#77 feat: 모바일 기능 구현 & 리팩토링,검색기능->구글로수정 해야함
  src/components/MoveDaySlider.tsx
  src/components/TwoButtonsModal.tsx
  src/components/mobile/CarouselTitleBox.tsx
  src/components/mobile/CommentCard.tsx
  src/components/mobile/ImageSlider.tsx
  src/components/mobile/ReviewCard.tsx
  src/components/mobile/bottomSheets/PlanPlaceSheet.tsx
  src/components/mobile/bottomSheets/PlanSheet.tsx
  src/components/mobile/bottomSheets/SelectTravelSheet.tsx
  src/components/mobile/home/CardSlide.tsx
  src/components/mobile/schedule/SelectDayModal.tsx
  src/components/web/schedule/AddedPlaceDetailModal.tsx
  src/components/web/travel-review/ReviewCard.tsx
  src/pages/mobile/addPlace/AddPlaceLayout.tsx
  src/pages/mobile/addPlace/ListView.tsx
  src/pages/mobile/details/HomeDetails.tsx
  src/pages/mobile/home/Home.tsx
  src/pages/mobile/home/More.tsx
  src/pages/mobile/mypage/Likes.tsx
  src/pages/mobile/mypage/Review.tsx
  src/pages/mobile/mypage/SelectPlace.tsx
  src/pages/mobile/mypage/WriteReview.tsx
  src/pages/mobile/schedule/Schedule.tsx
  src/pages/mobile/schedule/TravelMore.tsx
  src/pages/mobile/search/Search.tsx
  src/pages/mobile/travel-review/Review.tsx
  src/pages/mobile/travel-review/ReviewDetails.tsx
  src/pages/mobile/travel-review/TravelReview.tsx
  src/pages/mobile/travel-review/TravelogueDetails.tsx
  src/pages/web/mypage/WriteReview.tsx
  src/pages/web/travel-review/Review.tsx
  src/pages/web/travel-review/ReviewDetails.tsx
  src/pages/web/travel-review/TravelReview.tsx
  src/pages/web/travel-review/TravelogueDetails.tsx
  src/service/axios.ts
Labels: feat

#78 feat: P일 때 일정 부분 수정
  src/components/mobile/bottomSheets/PlanSheet.tsx
  src/components/mobile/schedule/PlanItem.tsx
  src/components/web/schedule/PlanItem.tsx
  src/pages/web/schedule/ScheduleDetails.tsx
  src/service/axios.ts
Labels: feat

#79 feat: 홈 디테일 리뷰&여행기 구분 , 리뷰&여행기 좋아요 기능 구현
  src/assets/styles/homeDetail.style.ts
  src/components/LikeCommentBox.tsx
  src/components/mobile/ReviewCard.tsx
  src/components/mobile/detail/ReviewCard.tsx
  src/components/mobile/detail/TripCard.tsx
  src/components/mobile/travelReview/TravelogueCard.tsx
  src/components/web/detail/ReviewCard.tsx
  src/components/web/detail/TripCard.tsx
  src/components/web/mypage/AddPlaceCard.tsx
  src/components/web/schedule/UpcomingSchedule.tsx
  src/components/web/travel-review/ReviewCard.tsx
  src/components/web/travel-review/TravelogueCard.tsx
  src/components/web/travel-review/TwoImageBox.tsx
  src/pages/mobile/details/HomeDetails.tsx
  src/pages/mobile/details/Reviews.tsx
  src/pages/mobile/travel-review/ReviewDetails.tsx
  src/pages/mobile/travel-review/TravelogueDetails.tsx
  src/pages/web/detail/Detail.tsx
  src/pages/web/mypage/MyLikes.tsx
  src/pages/web/mypage/WriteTravelouge.tsx
  src/pages/web/travel-review/ReviewDetails.tsx
  src/pages/web/travel-review/TravelogueDetails.tsx
  src/service/axios.ts
  src/types/travelreview.ts
Labels: feat

#80 chore: 이미지 에러 수정
  src/components/ImageView.tsx
  src/components/mobile/ReviewCard.tsx
  src/components/mobile/travelReview/TravelogueCard.tsx
  src/components/web/detail/ReviewCard.tsx
  src/components/web/mypage/ReviewCard.tsx
  src/components/web/travel-review/TwoImageBox.tsx
  src/pages/mobile/schedule/Schedule.tsx
  src/pages/mobile/schedule/TravelMore.tsx
  src/pages/mobile/travel-review/Review.tsx
  src/pages/mobile/travel-review/Travelogue.tsx
  src/pages/mobile/travel-review/TravelogueDetails.tsx
  src/pages/web/detail/Detail.tsx
  src/pages/web/mypage/MyReviews.tsx
  src/pages/web/travel-review/Review.tsx
  src/pages/web/travel-review/Travelogue.tsx
  src/pages/web/travel-review/TravelogueDetails.tsx
  src/types/mypage.ts
Labels: chore

#81 chore: 구글 로그인 배포 환경으로 변경
  src/pages/mobile/onboarding/Survey.tsx
  src/pages/web/onboarding/Survey.tsx
Labels: chore

#82 chore: 구글 로그인 배포 환경
  src/pages/mobile/onboarding/Onboarding.tsx
  src/pages/web/onboarding/Onboarding.tsx
Labels: chore
