Repository J-P-plan/J-P_FE2, pull requests merged in 2024-10, with the labels that each got.

#42 feat: web 리뷰 페이지 구현
  src/assets/styles/scheduleDetail.style.ts
  src/assets/styles/travelReview.style.ts
  src/components/mobile/CommentCard.tsx
  src/components/mobile/ReviewCard.tsx
  src/components/mobile/bottomSheets/PlanSheet.tsx
  src/components/web/travel-review/ReviewCard.tsx
  src/pages/mobile/onboarding/Survey.tsx
  src/pages/mobile/router.tsx
  src/pages/mobile/search/Search.tsx
  src/pages/mobile/travel-review/TravelReview.tsx
  src/pages/web/router.tsx
  src/pages/web/travel-review/Review.tsx
  src/pages/web/travel-review/ReviewDetails.tsx
  src/pages/web/travel-review/TravelReview.tsx
  src/pages/web/travel-review/Travelogue.tsx
  src/utils/axios.ts
  src/utils/staticDatas.ts
Labels: feat, chore

#43 feat: 마이페이지 마크업 & 이미지 로딩 훅
  src/assets/icons/HeartIcon.tsx
  src/components/web/home/SurroundingMoreAddCard.tsx
  src/components/web/home/SurroundingPlaceCard.tsx
  src/components/web/surroundingPlace/InfoModal.tsx
  src/hooks/useImgLoading.tsx
  src/pages/mobile/mypage/Likes.tsx
  src/pages/mobile/mypage/Review.tsx
  src/pages/web/Layout.tsx
  src/pages/web/mypage/MyLikes.tsx
  src/pages/web/mypage/MyReviews.tsx
  src/pages/web/mypage/MyTravel.tsx
  src/pages/web/mypage/MyTravelogue.tsx
  src/pages/web/mypage/MypageLayout.tsx
  src/pages/web/router.tsx
  src/utils/axios.ts
  src/utils/staticDatas.ts
Labels: feat

#44 feat: 일정 플랜 추가/수정 페이지 마크업
  src/assets/icons/BagIcon.tsx
  src/assets/icons/EatIcon.tsx
  src/assets/icons/EtcIcon.tsx
  src/assets/icons/PlanCalendarIcon.tsx
  src/assets/styles/scheduleDetail.style.ts
  src/components/mobile/bottomSheets/PlanSheet.tsx
  src/components/mobile/schedule/NextArrow.tsx
  src/components/mobile/schedule/PlanItem.tsx
  src/components/mobile/schedule/PlanList.tsx
  src/components/mobile/schedule/PrevArrow.tsx
  src/utils/staticDatas.ts
Labels: feat, chore

#45 feat: Search Page Markup
  src/components/mobile/CustomInput.tsx
  src/components/web/home/CardSlide.tsx
  src/pages/mobile/search/Search.tsx
  src/pages/web/home/Home.tsx
  src/pages/web/mypage/MyReviews.tsx
  src/pages/web/router.tsx
  src/pages/web/search/Search.tsx
  src/store/user.store.ts
Labels: feat

#47 feat: 검색 페이지 최근 검색어 수정, 리뷰 상세 페이지 댓글/사진 뷰어 구현
  src/assets/icons/SearchIcon.tsx
  src/assets/styles/travelReview.style.ts
  src/components/mobile/CommentCard.tsx
  src/components/mobile/CustomInput.tsx
  src/components/mobile/ReviewCard.tsx
  src/components/mobile/TravelogueCard.tsx
  src/components/web/travel-review/ReviewCard.tsx
  src/pages/mobile/home/Home.tsx
  src/pages/mobile/router.tsx
  src/pages/mobile/search/Search.tsx
  src/pages/web/router.tsx
  src/pages/web/travel-review/ImageViewer.tsx
  src/pages/web/travel-review/ReviewDetails.tsx
  src/pages/web/travel-review/TravelReview.tsx
  src/store/user.store.ts
  src/utils/staticDatas.ts
Labels: feat, chore

#49 feat: 여행기 페이지, 여행기 상세 페이지 구현
  src/assets/icons/CommentIcon.tsx
  src/assets/styles/home.style.ts
  src/assets/styles/homeDetail.style.ts
  src/assets/styles/travelReview.style.ts
  src/components/IconBox.tsx
  src/components/LikeCommentBox.tsx
  src/components/LoadingText.tsx
  src/components/TraveloguePlaceBox.tsx
  src/components/mobile/CommentCard.tsx
  src/components/mobile/ReviewCard.tsx
  src/components/mobile/home/TravelogueCard.tsx
  src/components/mobile/travelReview/TravelogueCard.tsx
  src/components/web/home/TravelogueCard.tsx
  src/components/web/travel-review/ReviewCard.tsx
  src/components/web/travel-review/TravelogueCard.tsx
  src/components/web/travel-review/TwoImageBox.tsx
  src/pages/mobile/details/HomeDetails.tsx
  src/pages/mobile/mypage/Review.tsx
  src/pages/mobile/travel-review/ReviewDetails.tsx
  src/pages/mobile/travel-review/TravelogueDetails.tsx
  src/pages/web/detail/Detail.tsx
  src/pages/web/router.tsx
  src/pages/web/travel-review/Review.tsx
  src/pages/web/travel-review/ReviewDetails.tsx
  src/pages/web/travel-review/TravelReview.tsx
  src/pages/web/travel-review/Travelogue.tsx
  src/pages/web/travel-review/TravelogueDetails.tsx
  src/utils/staticDatas.ts
Labels: feat, chore

#51 feat: 일정 상세 편집 모드 구현, TimeSwiper, JPToggle 컴포넌트 분리
  package-lock.json
  package.json
  src/components/JPToggle.tsx
  src/components/MoveDaySlider.tsx
  src/components/OneButtonModal.tsx
  src/components/TimeSwiper.tsx
  src/components/mobile/PrimaryButton.tsx
  src/components/mobile/schedule/PrevArrow.tsx
  src/components/web/schedule/PlanItem.tsx
  src/pages/mobile/addPlace/ListView.tsx
  src/pages/mobile/schedule/ScheduleLayout.tsx
  src/pages/web/schedule/ScheduleDetails.tsx
Labels: feat

#52 feat: 일정 생성 페이지 마크업, 장소 추가 모달, 시간 설정 모달 구현
  package-lock.json
  src/components/OneButtonModal.tsx
  src/components/TimeSwiper.tsx
  src/components/mobile/PrimaryButton.tsx
  src/components/mobile/schedule/SelectDayModal.tsx
  src/components/web/home/CardSlide.tsx
  src/components/web/schedule/AddPlaceCard.tsx
  src/components/web/schedule/CitySlider.tsx
  src/components/web/schedule/RecommendCard.tsx
  src/components/web/schedule/ScheduleCard.tsx
  src/components/web/schedule/SelectDayModal.tsx
  src/components/web/search/ResultsCard.tsx
  src/components/web/search/SearchModal.tsx
  src/hooks/useAddPlace.tsx
  src/hooks/useSearch.tsx
  src/index.css
  src/pages/mobile/addPlace/ListView.tsx
  src/pages/mobile/schedule/Calendar.tsx
  src/pages/web/Header.tsx
  src/pages/web/Layout.tsx
  src/pages/web/detail/SurroundingMore.tsx
  src/pages/web/home/More.tsx
  src/pages/web/router.tsx
  src/pages/web/schedule/CreatePlace.tsx
  src/pages/web/schedule/CreateSchedule.tsx
  src/pages/web/schedule/Schedule.tsx
  src/pages/web/search/Search.tsx
  src/store/modal.store.ts
  src/utils/staticDatas.ts
Labels: feat

#53 feat: 마이페이지 리뷰쓰기, 여행기쓰기 페이지 마크업
  src/assets/icons/HalfStarIcon.tsx
  src/components/ActionButton.tsx
  src/components/OneButtonModal.tsx
  src/components/PrimaryButton.tsx
  src/components/TwoButtonsModal.tsx
  src/components/mobile/StyledToast.tsx
  src/components/web/Container.tsx
  src/components/web/mypage/AddPlaceCard.tsx
  src/components/web/mypage/MyTravelCard.tsx
  src/components/web/mypage/SelectPlaceBar.tsx
  src/components/web/mypage/SelectTravelModal.tsx
  src/components/web/search/SearchBar.tsx
  src/hooks/useImageUpload.tsx
  src/hooks/useImagesUpload.tsx
  src/pages/mobile/addPlace/ListView.tsx
  src/pages/mobile/mypage/WriteReview.tsx
  src/pages/mobile/onboarding/Survey.tsx
  src/pages/web/Header.tsx
  src/pages/web/Layout.tsx
  src/pages/web/mypage/EditProfile.tsx
  src/pages/web/mypage/MyLikes.tsx
  src/pages/web/mypage/MyReviews.tsx
  src/pages/web/mypage/MyTravel.tsx
  src/pages/web/mypage/MyTravelogue.tsx
  src/pages/web/mypage/MypageLayout.tsx
  src/pages/web/mypage/WriteReview.tsx
  src/pages/web/mypage/WriteTravelouge.tsx
  src/pages/web/router.tsx
  src/pages/web/schedule/CreatePlace.tsx
  src/pages/web/schedule/CreateSchedule.tsx
  src/pages/web/travel-review/ImageViewer.tsx
  src/store/modal.store.ts
  src/utils/staticDatas.ts
Labels: feat

#55 chore: web 온보딩 페이지 및 구글 로그인 구현
  src/assets/styles/home.style.ts
  src/components/ProfileNoImg.tsx
  src/components/web/Header.tsx
  src/components/web/home/CardSlide.tsx
  src/components/web/mypage/AddPlaceCard.tsx
  src/components/web/mypage/SelectPlaceBar.tsx
  src/components/web/mypage/SelectTravelModal.tsx
  src/components/web/search/ResultsCard.tsx
  src/components/web/search/SearchBar.tsx
  src/components/web/travel-review/ReviewCard.tsx
  src/components/web/travel-review/TravelogueCard.tsx
  src/pages/mobile/onboarding/Onboarding.tsx
  src/pages/mobile/onboarding/Survey.tsx
  src/pages/web/Header.tsx
  src/pages/web/Layout.tsx
  src/pages/web/detail/Detail.tsx
  src/pages/web/detail/SurrondingPlace.tsx
  src/pages/web/detail/SurroundingMore.tsx
  src/pages/web/home/Home.tsx
  src/pages/web/mypage/EditProfile.tsx
  src/pages/web/mypage/MypageLayout.tsx
  src/pages/web/mypage/WriteReview.tsx
  src/pages/web/onboarding/Onboarding.tsx
  src/pages/web/onboarding/Survey.tsx
  src/pages/web/router.tsx
  src/pages/web/schedule/Schedule.tsx
  src/pages/web/search/Search.tsx
  src/pages/web/travel-review/ReviewDetails.tsx
  src/pages/web/travel-review/TravelReview.tsx
  src/pages/web/travel-review/TravelogueDetails.tsx
  src/store/user.store.ts
  src/types/mypage.ts
  src/utils/axios.ts
  src/utils/staticDatas.ts
Labels: chore
