Repository J-P-plan/J-P_FE2, pull requests merged in 2024-09, with the labels that each got.

#32 feat: 리뷰 쓰기 페이지 & NotButtonModal & Home Detail 이미지 로딩 개선
  package-lock.json
  package.json
  src/assets/icons/ImageAddIcon.tsx
  src/assets/styles/homeDetail.style.ts
  src/components/mobile/NobuttonModal.tsx
  src/hooks/useImageUpload.tsx
  src/hooks/useModal.tsx
  src/pages/mobile/addPlace/ListView.tsx
  src/pages/mobile/addPlace/Mapview.tsx
  src/pages/mobile/details/HomeDetails.tsx
  src/pages/mobile/mypage/SelectPlace.tsx
  src/pages/mobile/mypage/WriteReview.tsx
  src/pages/mobile/search/Search.tsx
  src/store/writeReview.store.ts
Labels: feat

#33 feat: 일정 생성/상세 일정 페이지 구현
  package-lock.json
  package.json
  src/assets/icons/CardIcon.tsx
  src/assets/icons/FileCheckIcon.tsx
  src/assets/icons/PlanCalendarIcon.tsx
  src/assets/icons/TicketIcon.tsx
  src/assets/icons/TrainIcon.tsx
  src/assets/icons/TrashIcon.tsx
  src/assets/styles/scheduleDetail.style.ts
  src/components/mobile/ImageModal.tsx
  src/components/mobile/scheduleSort/PlanItem.tsx
  src/components/mobile/scheduleSort/PlanList.tsx
  src/index.css
  src/pages/mobile/schedule/Details.tsx
  src/pages/mobile/schedule/ScheduleLayout.tsx
  src/store/JPType.store.ts
  src/types/schedule.ts
  src/utils/staticDatas.ts
Labels: feat

#34 chore: ImageModal -> ImageSlider 이름 변경, reviewStore 상태 수정
  src/components/mobile/ImageSlider.tsx
  src/pages/mobile/travel-review/ReviewDetails.tsx
  src/pages/mobile/travel-review/TravelLogDetails.tsx
  src/pages/mobile/travel-review/TravelReview.tsx
  src/store/travelReview.store.ts
Labels: chore

#36 feat: 일정 Day 부분, 일정 상세 페이지 수정
  src/assets/icons/AddSquareIcon.tsx
  src/assets/icons/CarIcon.tsx
  src/assets/icons/CardIcon.tsx
  src/assets/icons/TicketIcon.tsx
  src/assets/styles/scheduleDetail.style.ts
  src/components/mobile/SlideArrows/NextArrow.tsx
  src/components/mobile/SlideArrows/PrevArrow.tsx
  src/pages/mobile/schedule/Details.tsx
  src/utils/staticDatas.ts
Labels: feat

#38 chore: 일정을 삭제할까요? 모달 구현
  src/assets/styles/modal.style.ts
  src/components/mobile/TravelogueCard.tsx
  src/components/mobile/home/TravelogueCard.tsx
  src/components/mobile/scheduleSort/PlanItem.tsx
  src/components/mobile/scheduleSort/PlanList.tsx
  src/components/web/home/CardSlide.tsx
  src/components/web/home/TravelogueCard.tsx
  src/components/web/home/TravelogueCardSlide.tsx
  src/index.css
  src/pages/mobile/Layout.tsx
  src/pages/mobile/addPlace/Mapview.tsx
  src/pages/mobile/details/NearPlace.tsx
  src/pages/mobile/home/Home.tsx
  src/pages/mobile/mypage/Likes.tsx
  src/pages/mobile/mypage/Travelogue.tsx
  src/pages/mobile/router.tsx
  src/pages/mobile/schedule/Details.tsx
  src/pages/mobile/travel-review/TravelReview.tsx
  src/pages/mobile/travel-review/Travelogue.tsx
  src/pages/mobile/travel-review/TravelogueDetails.tsx
  src/pages/web/home/Home.tsx
  src/utils/staticDatas.ts
Labels: chore

#39 feat: web page 마크업 & useModal 삭제
  src/assets/styles/modal.style.ts
  src/assets/styles/nearplace.style.ts
  src/components/mobile/NobuttonModal.tsx
  src/components/mobile/OneButtonModal.tsx
  src/components/mobile/ReviewCard.tsx
  src/components/mobile/TwoButtonsModal.tsx
  src/components/mobile/googleMap/RenderGoogleMap.tsx
  src/components/web/home/CardSlide.tsx
  src/components/web/home/PlaceCard.tsx
  src/components/web/home/SurroundingMoreAddCard.tsx
  src/components/web/home/SurroundingPlaceCard.tsx
  src/hooks/useModal.tsx
  src/pages/mobile/addPlace/ListView.tsx
  src/pages/mobile/details/NearPlace.tsx
  src/pages/mobile/details/Reviews.tsx
  src/pages/mobile/mypage/WriteReview.tsx
  src/pages/mobile/schedule/Details.tsx
  src/pages/mobile/search/Search.tsx
  src/pages/web/Layout.tsx
  src/pages/web/detail/Detail.tsx
  src/pages/web/detail/SurrondingPlace.tsx
  src/pages/web/detail/SurroundingMore.tsx
  src/pages/web/home/Home.tsx
  src/pages/web/home/More.tsx
  src/pages/web/router.tsx
  src/store/display.store.ts
  src/types/home.details.ts
  src/utils/staticDatas.ts
Labels: chore

#40 feat: Web 주변 여행지 페이지 모달 마크업 & API 중복 코드 제거
  package-lock.json
  package.json
  src/assets/styles/modal.style.ts
  src/components/mobile/NobuttonModal.tsx
  src/components/mobile/home/CardSlide.tsx
  src/components/web/home/PlaceAddModal.tsx
  src/components/web/surroundingPlace/InfoModal.tsx
  src/components/web/surroundingPlace/NoScheduleModal.tsx
  src/components/web/surroundingPlace/ScheduleModal.tsx
  src/components/web/surroundingPlace/SuccessModal.tsx
  src/main.tsx
  src/pages/mobile/City.tsx
  src/pages/mobile/Layout.tsx
  src/pages/mobile/details/HomeDetails.tsx
  src/pages/mobile/details/NearPlace.tsx
  src/pages/mobile/details/Reviews.tsx
  src/pages/mobile/home/More.tsx
  src/pages/mobile/mypage/EditProfile.tsx
  src/pages/mobile/mypage/MyPageLayout.tsx
  src/pages/mobile/onboarding/Onboarding.tsx
  src/pages/mobile/onboarding/Survey.tsx
  src/pages/web/detail/Detail.tsx
  src/pages/web/detail/SurrondingPlace.tsx
  src/pages/web/detail/SurroundingMore.tsx
  src/pages/web/home/More.tsx
  src/store/user.store.ts
  src/utils/axios.ts
  src/utils/axios.type.ts
Labels: feat

#41 chore: 바텀시트 수정, 리뷰 필터 수정, survey page style 수정
  src/components/mobile/bottomSheets/PlanPlaceSheet.tsx
  src/components/mobile/bottomSheets/PlanSheet.tsx
  src/index.css
  src/pages/mobile/onboarding/Survey.tsx
  src/pages/mobile/schedule/Details.tsx
  src/pages/mobile/travel-review/TravelReview.tsx
  src/utils/staticDatas.ts
Labels: feat, chore
